# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff840b6986e31611485870614629e6f0ea0d768ef373873fe7da534807f1af4a0025a3d76b240163694050a1f6d7ded317b86ae5617415587ab9c02bfdf2aca9

test:
  secret_key_base: 8527545d6735afe3d4f40429bd827058d0cfb36ccc7131bcfb1d2bc0d513d984ea40faef7f07276433910fb3e68f89c643f670a3d1434f1df037737fe6d8a54a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
